config/routes.rb
Rails.application.routes.draw do
  resources :todos

  devise_for :users
  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  # attr_accessible :description, :completed, :user_id
  belongs_to :user
  after_create :send_webhook
  after_save :send_webhook
  after_update :send_webhook

  def delete
    super
    send_webhook
  end

  def send_webhook
    HTTParty.get("http://localhost:2020/update_todos?userid=#{self.user_id}")
  end
end

app/models/todo_resetter.rb
class TodoResetter
  include ::ScheduledJob

  def perform
    puts "#####"
    puts "Refreshing Todos"
    puts "#####"
    Todo.where(completed: true).each {|todo| todo.completed = false; todo.save}
  end

  def self.time_to_recur(last_run_at)
    last_run_at + 1.minutes
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  protect_from_forgery
  # GET /todos
  # GET /todos.json
  def index
    @todos = current_user.todos
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo[:description] = @todo[:description].titleize
    @todo[:user_id] = current_user.id
    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.delete
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    params.require(:todo).permit(:description, :recurrance, :completed, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35727/livereload.js?snipver=1"></' + 'script>')</script>
    <link rel="stylesheet" type="text/css" href="http://localhost:8000/css/app.css">
    <%= csrf_meta_tags %>
    <% if current_user %>
      <meta name="user_id" content="<%= current_user.id %>">
    <% end %>
  </head>
  <body>
    <% if notice %>
      <div class="notice">
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert">
        <p><%= alert %></p>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<script type="text/javascript" src="http://localhost:8000/js/lib.js"></script>
<script type="text/javascript" src="http://localhost:8000/js/app.js"></script>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.description %></td>
        <td><%= todo.completed %></td>
        <td><%= todo.user_id %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<p>
  <strong>User:</strong>
  <%= @todo.user_id %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>